prueba: Main.cpp Parser.cpp SymbolTable.cpp Code.cpp Parser.h Code.h SymbolTable.h 
	g++ -o prueba Main.cpp Parser.cpp SymbolTable.cpp Code.cpp Parser.h Code.h SymbolTable.h

Traductor: Traductor.cpp Parser.cpp SymbolTable.cpp Code.cpp Parser.h Code.h SymbolTable.h 
	g++ -o Traductor Traductor.cpp Parser.cpp SymbolTable.cpp Code.cpp Parser.h Code.h SymbolTable.h
